name: CI

on:
  push:
    branches:
      - develop
      - feature/*
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 24

      - run: |
          corepack enable
          corepack prepare yarn@4.13.0 --activate
          yarn install --immutable

      - run: yarn tsc --noEmit

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 24

      - run: |
          corepack enable
          corepack prepare yarn@4.13.0 --activate
          yarn install --immutable

      - run: yarn lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 24

      - run: |
          corepack enable
          corepack prepare yarn@4.13.0 --activate
          yarn install --immutable

      - run: yarn test